AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CICD Demo Lambda cloudformation

Resources:
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ../Lambda/
      Handler: HelloWorld.lambda_handler
      Runtime: python3.8
      Description: 'Lambda Function CI/CD demo'
      MemorySize: 128
      Timeout: 300
      Role: 
        !Join
          - ''
          - - 'arn:aws:iam::'
            - !Ref AWS::AccountId
            - ':role/integration-lambda-execution'
            
